### ISSUE TITLE
Misleading term in the docs

### ISSUE THREAD

**Issue by bakerhassan** [andrewjahn/AndysBrainBook#10]
In this doc https://andysbrainbook.readthedocs.io/en/latest/fMRI_Short_Course/Statistics/03_Stats_HRF_Overview.html#what-if-the-hrfs-overlap
Do you really mean that the HRFs are convolved? The figure shows that you just sum them, convolution will create a new filter (or HRF) that has a larger domain that the sum.

**Comment by andrewjahn** [comment]
Yes, you're right; I've corrected this in the latest upload. Thanks!
