### ISSUE TITLE
REgarding your help

### ISSUE THREAD

**Issue by INNFINITEMINDS** [andrewjahn/AndysBrainBook#11]
Respected Sir,
![image](https://user-images.githubusercontent.com/28722237/76495160-8357e600-63f3-11ea-9e20-20d209998d8b.png)

HOW CAN I CONVERT MY DATA  TO SOURCE LOCALISED DATA?
I AM NEW TO THIS ..PLEASE GIVE SOME DIRECTION..
HOW CAN I PERFORM /GO FROM STEP 1 TO STEP 2 from the above image ?
HOW CAN I PRODUCE **nAm vs ms GRAPH (DATA)**?

awaiting for your response..
thanks,
arpit

**Comment by andrewjahn** [comment]
Sorry, I don't know how to analyze that type of data!
