### ISSUE TITLE
resampling data question

### ISSUE THREAD

**Issue by AtomicNess123** [andrewjahn/AndysBrainBook#13]
Dear Andy, excellent material.

I am trying at the moment to resample a 61x73x61, time series of fmri data to something smaller to work with deep learning which is computationally very expensive.  I should end up with a smaller cube (maybe 30x30x30), but I don't know how to go about it. Once the data is analyzed, I should upsample it back to its original shape. Any advice would be welcome. Thanks.

**Comment by andrewjahn** [comment]
Hi Gahamelas,

You can use a resampling program such as AFNI's 3dresample to change the voxel sizes and consequently decrease the resolution, e.g.:

3dresample -prefix run01_rs.nii -dxyz 5 5 5 -input run01.nii

You will need to play around with the dimensions in the -dxyz option until you get the resolution you want, but I would start there.

-Andy
