### ISSUE TITLE
 [ERROR] required input file “sift_1mio.tck” not found.

### ISSUE THREAD

**Issue by neoana** [andrewjahn/AndysBrainBook#15]
Hi friend. 
I am new to MRtrix3. In the tutorial “https://andysbrainbook.readthedocs.io/en/latest/MRtrix/MRtrix_Course/MRtrix_08_Connectome.html”, “Creating the Connectome”, I get an error : [ERROR] required input file “sift_1mio.tck” not found.
I don’t find sift_1_mio.tck file in my computer. Where to find this file? I use ds001226 from openneuro.org. Thanks.

**Comment by andrewjahn** [comment]
Hi there, did you do all of the preceding steps? It should have been created by the previous tckgen command; and I may have updated the tutorial in the meantime. Try it again, and if you still need help feel free to email me at my University of Michigan email address.

-Andy
