### ISSUE TITLE
How to merge data

### ISSUE THREAD

**Issue by Huiling9496** [andrewjahn/AndysBrainBook#16]
Hello, you said "Once the data have been smoothed, the directories will contain files called “stfMRI_SOCIAL_LR.nii” and “stfMRI_SOCIAL_RL.nii”. We will be combining these into a single dataset".

So, my question is how to combine "stfMRI_SOCIAL_LR.nii" and “stfMRI_SOCIAL_RL.nii”.  

Thank you.

**Comment by andrewjahn** [comment]
You can merge them with a command like fslmerge, e.g.:

fslmerge -t merged.nii stfMRI_SOCIAL_LR.nii stfMRI_SOCIAL_RL.nii

I think those files I mention are from an old tutorial that may no longer be supported, but in any case that is how you merge two separate images.

-Andy
