### ISSUE TITLE
Consistency of trial info in timing files example

### ISSUE THREAD

**Issue by mwvoss** [andrewjahn/AndysBrainBook#20]
This is minor but should be an easy fix that'll help students track conversion of timing files for task analysis in FSL.

Panel B in the Timing Files figure is inconsistent with the trial list in events.tsv and output in panel C
https://andysbrainbook.readthedocs.io/en/latest/fMRI_Short_Course/Statistics/05_Creating_Timing_Files.html

**Comment by andrewjahn** [comment]
Thanks for pointing that out! I've updated each of those figures in the FSL, AFNI, and SPM tutorials.

-Andy
