### ISSUE TITLE
Missing "more info" box

### ISSUE THREAD

**Issue by anthilemoon** [andrewjahn/AndysBrainBook#21]
Hi Andy!

First, I'm very grateful for this resource. Thanks so much for putting it together.

[This page](https://github.com/andrewjahn/AndysBrainBook/blob/master/docs/unix/Unix_06_IfElse.rst) says to click on a link in the "more info" box for instructions about how to download the Flanker dataset, install FSL, and what skull-stripping is, which I think is missing on the page.

I tried CMD+F for "more info" and "skull-stripping" and couldn't find it.

Please let me know if I'm not looking in the right place.

Thank you,
Anne-Laure.

**Comment by andrewjahn** [comment]
Thanks for letting me know! I've changed it to a link for the FSL course; the text was originally copied from a script for a YouTube video, hence the confusion.

-Andy
