### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by opennog** [andrewjahn/AndysBrainBook#30]
Hey Andy 
Very nice tutorials you are providing! :) However I would like to ask you if you could make available some sample data you are using in the tutorials, particularly for the PETSurfer one. 

Thank you very much!
Óscar

**Comment by andrewjahn** [comment]
Hi Óscar,

The PETSurfer section is still under development, so I haven't linked it to a specific dataset; you should be able to use it with the same dataset that is used in the FreeSurfer tutorial. Besides that, please let me know if there are other datasets that are missing from other modules; I apologize for getting back to this rather late, so I'll keep this open for a couple more weeks if you'd like to reply.


Best,

-Andy
