### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by ZBDat** [andrewjahn/AndysBrainBook#31]
Hello Andy! Thanks for the great course you provide here! I just wonder if and how can I cite some chapter (or the book) in this repo? Is there any guidance on formats like title, autor, etc.?

**Comment by andrewjahn** [comment]
Hi there,

I haven't thought about that; I suppose at this point you could just cite the link, similar to how some people cite the AFNI or FSL link when they talk about their methods in a paper. I appreciate it!

Thanks!

-Andy
