### ISSUE TITLE
Citation guide

### ISSUE THREAD

**Issue by DanNBullock** [andrewjahn/AndysBrainBook#33]
I recognize that this resource may not have been published in any traditional sense, but there may be those out there (like myself) that may like to cite this substantial (and precedent setting) piece of work.  Do you have any recommended or desired citation protocol?  If so, it may be helpful to include it somewhere in the documentation itself.  Getting a DOI might be a big help for this as well (may be via [zenodo](https://zenodo.org/)).

**Comment by DanNBullock** [comment]
I just saw that you closed an issue about this, apologies!

**Comment by andrewjahn** [comment]
Hi Dan,

Thanks for the suggestion! I created a DOI through Zenodo, and you can use this as a template; let me know what you think:

"We followed the AFNI preprocessing pipeline as outlined in Andy's Brain Book (Jahn, 2022. doi:10.5281/zenodo.5879293)."



Best,

-Andy
