### ISSUE TITLE
Coregistration dependency is fishy

### ISSUE THREAD

**Issue by HuangHam** [andrewjahn/AndysBrainBook#35]
Hey Andy, Just upfront your brain book is a life saver! Thank you! I noticed something in your scripting section. In the tutorial, every step takes in a dependency of the previous step. This is manifested in your github script also except for the segmentation. So the segmentation is supposed to depend on the output of the coregistered anatomical image: cfg_dep('Coregister: Estimate & Reslice: ...) but in your script, this is replaced with the explicit directory for this coregistered image. This change was not mentioned anywhere in the tutorial or the video. Why did you do that? Is it because there is a bug in the dependency functionality of SPM?

**Comment by andrewjahn** [comment]
Hi there,

Yes, I think that was just a slip-up when taking the screenshot for that particular tutorial; to make it as generalizable as possible, I would specify it as a dependency. I'll try to fix that as soon possible. Thanks for pointing that out!

-Andy
