### ISSUE TITLE
How do you do this on a group-level?

### ISSUE THREAD

**Issue by JoschaBoehnlein** [andrewjahn/AndysBrainBook#4]
Hello Dr. Jahn,

thank you very much for this helpful and concise explanation of PPI! I could follow it very easily and feel that I have now a better grasp of what PPI actually does and how to use it.
My question, however, is the following: How do you use it on a group level? As far as I understood it, you only used the scans of one person and extracted the VOI of the same person. In my research, I would like to do a PPI analysis over one group of persons and additionally compare to groups in respect to their PPI. How would I do that? Could you maybe point me to an explanation of this point?

I hope I don't steal your time with this question, feel free not to answer if you feel that you don't want to. 

Best wishes,
Joscha Böhnlein

**Comment by andrewjahn** [comment]
Hi Joscha,

You can do this by combining the individual PPI images into a second-level analysis, or doing an ROI analysis over all of the subjects; the PPI maps are beta values that can be analyzed just like parameter estimates from an fMRI study.

If you want to discuss this more, feel free to drop me a line at ajahn@umich.edu; I don't check my github that often.

-Andy
