### ISSUE TITLE
Text missing in SDM description page

### ISSUE THREAD

**Issue by ines-almeida** [andrewjahn/AndysBrainBook#44]
I believe this SDM section is missing text, as last sentence is interrupted and the section has much less lenght than the ALE and the online meta-analysis tools:
https://andysbrainbook.readthedocs.io/en/latest/MetaAnalysis/MetaAnalysis_ShortCourse/MetaAnalysis_02_SeedBasedDMapping.html

**Comment by andrewjahn** [comment]
Hi there,

Yes, I am still working on that, and I left it unfinished; I intend to get back to it soon!


Best,

-Andy
