### ISSUE TITLE
The URL to BIDS_Tutorial is missing.

### ISSUE THREAD

**Issue by zrmor** [andrewjahn/AndysBrainBook#45]
It seems that the link pointing to BIDS_Tutorial on google drive is changed.
Where? Section "[BIDS App Tutorial #1: MRIQC](https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/MRIQC.html#bids-app-tutorial-1-mriqc)", subsection "[MRIQC Tutorial](https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/MRIQC.html#mriqc-tutorial)" Line: (you can download the BIDS output data [here](https://drive.google.com/drive/folders/11qNNVmD-T8OoZy9NFqHjcleWIcso6ZDI?usp=sharing)).

**Comment by andrewjahn** [comment]
Hi there,

Apologies for the late reply! The link has been updated.


Best,

-Andy
