### ISSUE TITLE
MRtrix Tutorial #10: Group-Level Analysis

### ISSUE THREAD

**Issue by YYaHan** [andrewjahn/AndysBrainBook#47]
Hi @andrewjahn , 
Thanks for your great tutorial and I learned a lot.

I want to ask you when will you finish the Tutorial #10. I can't wait to read this chapter and try it!!

Thanks.

**Comment by andrewjahn** [comment]
Hi there,

That is something I have been meaning to do for a while, but I have gotten sidetracked with other projects; I will try to get to it as soon as I can!


Best,

-Andy
